echo "-----------------Map--------------------------"
echo "Node2"
python info.py | grep " Map task" | grep "ClusterNode2 \!"
echo "Node3"
python info.py | grep " Map task" | grep "ClusterNode3 \!"
echo "Node4"
python info.py | grep " Map task" | grep "ClusterNode4 \!"
echo "-----------------Reduce--------------------------"
echo "Node2"
python info.py | grep " Red task" | grep "ClusterNode2 \!"
echo "Node3"
python info.py | grep " Red task" | grep "ClusterNode3 \!"
echo "Node4"
python info.py | grep " Red task" | grep "ClusterNode4 \!"
echo "-----------------Ratio------------------------"
python info.py | tail -1
